{% set version = "0.4-7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gridbase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gridBase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gridBase/gridBase_{{ version }}.tar.gz
  sha256: be8718d24cd10f6e323dce91b15fc40ed88bccaa26acf3192d5e38fe33e15f26

build:
  merge_build_host: true  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gridBase')"           # [not win]
    - "\"%R%\" -e \"library('gridBase')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gridBase
  license: GPL-2.0-or-later
  summary: Integration of base and grid graphics
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
