appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nlgMyJ+PbwDeGpeMAW3b6vp4vIP5JJUoYY5cFtA8UCBU6yWqyqVpjRAO0zLzoahzviucSMQankKaPxcBZ8hEMEmYr9mi/FBdyHcLkk+QMzRL5CQsuzii/jQZWmKNILRmr6gT44Qk/OdDGYvDSUOgNyHky6K8B37AXRhnUqbMZf0mQPDBz2b5UeYuXXD8gQec7wk41WEz9vc5FhbPGHi+daEh18cTTFl+XhGu+FdCiJvm2d+5Oatvmz5ZasyCijgcAaWKGegge8Vwx0dEPPL2NfWAzq6LHKW/5hMewz1FlTKajYsPbasY9H1oao9F/O2bfR/v4f5bQVq97MJJTCNxpbsCY3RvffzhbOYK+p5dKjmDkmjeKQ5lIVKiCNzqDsyEoeh99wQCdLY76Kz8Rf+6UoZ0KzZHdJJyXu8leEZhYEgIwD9aFg2h80pHvMF7EcRNw9vvarDce/eASGXNcns4STVFumUiAPXTEq5zDfAUuTnUKWg9zoeKpK2q3+jMnkMyEIZintKLMiqrLtAcG9m2Ds4RhbmTQQ/CUYNNdJ6bX2yMJDHgai3mwS+WO/rsnyriLNn4J6e1K0mwaNuRU2LFZupmlBSQKV4HSs69+RVQvfu2J1LgoIfaSiY1fH1IcHFLDbkEmUlZmYhmTzXpo2S0BXHvPs9n3kSLk0HK633peps=}
